#!/usr/bin/env bash
#Tessdf
while IFS=: read -r username password user_id  group_id _ home_dir shell; do

	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $username "


done < /etc/passwd
